CREATE TABLE IF NOT EXISTS COMMENTS(
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    POST_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    UPDATED_AT BIGINT NOT NULL,
    CREATED_AT BIGINT NOT NULL
);