CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR UNIQUE NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    IMAGE_URL TEXT NULL,
    FRIEND_COUNT BIGINT NOT NULL DEFAULT 0,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD TEXT NOT NULL,
    CREATED_AT BIGINT NOT NULL,
    UPDATED_AT BIGINT NOT NULL
);