CREATE TABLE IF NOT EXISTS COMMENTS(
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    POST_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    UPDATED_AT BIGINT NOT NULL,
    CREATED_AT BIGINT NOT NULL,
    CONSTRAINT fk_comments_user FOREIGN KEY(USER_ID) REFERENCES USERS(id),
    CONSTRAINT fk_comments_post FOREIGN KEY(POST_ID) REFERENCES POSTS(id)
);